descriptionFormat: ''
handle: clothing
hasDimensions: true
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: false
name: Clothing
productFieldLayouts:
  958620d5-f689-414b-89cb-5fa1faf7cb70:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
productTitleFormat: ''
siteSettings:
  af25f770-8ab6-4405-9425-758c043e42bb: # TSD
    hasUrls: true
    template: shop/products/_product
    uriFormat: 'shop/products/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
