field: b3eed510-dfb3-497c-9d9e-c7b1677cd0f4 # Post Content
fieldLayouts:
  127e6687-3f95-4849-9788-30acbad66043:
    tabs:
      -
        elements:
          -
            fieldUid: e555b0ed-9568-4e9e-8568-13e3cd596206 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e555b0ed-9568-4e9e-8568-13e3cd596206: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:c2d2192c-8775-4172-a003-98b4dc07b709' # Blog
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:c2d2192c-8775-4172-a003-98b4dc07b709' # Blog
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
