fieldLayouts:
  a69f91b8-7923-496d-ab2e-d9ce984b037e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 5ddf7da4-43cc-4f83-ae2e-bb04a4c94134 # category Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  af25f770-8ab6-4405-9425-758c043e42bb: # TSD
    hasUrls: true
    template: blog/_category
    uriFormat: 'blog/category/{slug}'
structure:
  maxLevels: 1
  uid: bea2969d-b78c-45c4-aafb-904005301fcd
