tabs:
  -
    elements:
      -
        fieldUid: d76b32b9-39c5-495a-9650-ec8b893e61a4 # Bio
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: information
    sortOrder: 1
