contentColumnType: string
fieldGroup: 228e5f39-f37b-4725-9441-d67e3ba47be5 # Blog Post Fields
handle: postCategories
instructions: ''
name: 'Post Categories'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:d4be2444-fcba-4b18-a727-d1108b1d03d9' # Blog Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
