contentColumnType: text
fieldGroup: aec739e8-0f14-4f6b-9ffc-519a2318c99b # Global Fields
handle: siteInformation
instructions: ''
name: 'Site Information'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
