dateModified: 1617565546
email:
  fromEmail: daviesg77@gmail.com
  fromName: TSD
  replyToEmail: null
  template: _includes\email-template
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  comments-work:
    edition: standard
    enabled: true
    licenseKey: NUHGWXQUG0ETBK1GI38SR047
    schemaVersion: 1.0.3
  commerce:
    edition: lite
    enabled: false
    licenseKey: 7E4CMWA2L1F1DQQGYORAW2P5
    schemaVersion: 3.2.18
  freeform:
    edition: pro
    enabled: true
    licenseKey: A1PC0K4DGIVYJ1BFXLDYXLQW
    schemaVersion: 3.3.0
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: daviesg77@gmail.com
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      clientDigestFrequency: 1
      clientDigestRecipients: daviesg77@gmail.com
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: daviesg77@gmail.com
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: tailwind.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: ''
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      scriptInsertLocation: footer
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  froala-editor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.1
  videos:
    edition: standard
    enabled: true
    licenseKey: C0YW4RSXWLKI7GKKJHJEQC2X
    schemaVersion: 1.0.3
system:
  edition: pro
  live: true
  name: TrainSimDepot
  retryDuration: null
  schemaVersion: 3.6.7
  timeZone: America/Los_Angeles
