enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  af25f770-8ab6-4405-9425-758c043e42bb: # TSD
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
