enableVersioning: true
handle: submit
name: submit
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af25f770-8ab6-4405-9425-758c043e42bb: # TSD
    enabledByDefault: true
    hasUrls: true
    template: _singles\submit
    uriFormat: submit
type: single
